# Generated by Django 4.1.3 on 2022-11-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Service",),
    ]
