# Generated by Django 4.1.2 on 2022-12-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_services_delete_schedule"),
    ]

    operations = [
        migrations.RemoveField(model_name="services", name="budget",),
        migrations.AddField(
            model_name="services", name="value", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="services", name="job_date", field=models.DateTimeField(),
        ),
    ]
