# Generated by Django 4.1.2 on 2022-12-03 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_remove_services_budget_services_value_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="services", old_name="job_date", new_name="job_date_time",
        ),
    ]
